### ISSUE TITLE
Verify behavior of pipe for `use_dh=True`

### ISSUE THREAD

**Issue by marcusfuchs** [bramvdh91/modelica-annex60#23]
#22 introduces the parameter `use_dh` as used in `Annex60.Fluid.FixedResistances.FixedResistanceDpM`. In the implementation of #22, `use_dh` is set to false, causing the same behavior as we have been working on from the start. This issue is to also verify the behavior for `use_dh = True`.

**Comment by bramvdh91** [comment]
#22 is now merged and closed. Should we delete the branch issue264_pipeUseCases?

**Comment by marcusfuchs** [comment]
Yes, I just deleted it. I'll start a new branch for this issue.

**Comment by bramvdh91** [comment]
I opened `pipe_issue23_useDH` for this.

**Comment by bramvdh91** [comment]
@marcusfuchs , could you briefly explain what is the use of having `use_dh` set to false? I think it is okay to propagate this parameter to the top level of our pipes, but the hydraulic diameter is (among other parameters) needed to calculate the thermal resistance and capacitance of the pipe. 
Hence, I would suggest not to disable the input for `dh` when `use_dh` is false at the top level.

Probably, here it is also good to have some standard pipe sizes in a database, as is already the case for double pipes. If you agree, I can implement this again based on IsoPlus data sheets.

**Comment by marcusfuchs** [comment]
As I understand it, this has mainly two reasons:
1. Consistency with the rest of the Annex 60 Library code base. All other similar models in A60 have this parameter and default set to `False` (`use_dh=False` has also been the default setting in e.g. the Buildings library for quite some time I think)
2. Good default for quick studies of a prototype system. I agree that for a lot of studies (most of ours at Aachen included) we use a hydraulic diameter value for calculations. The intended behavior of `use_dh=False` is to only give a specific pressure loss (e.g. 200 Pa/m). If you do a quick prototype study, you can thus just click together a pipe network and it will "design itself diameter-wise" so to say.

But you are right, the hydraulic diameter is needed for the thermal properties. Thus, I see three options: 
- Drop the consistency with the rest of A60 (probably not a good idea)
- Change the default approach of A60 (probably hard to do)
- Calculate `dh` also for the case that `use_dh=False` based on the specific pressure loss. And write a good documentation about this within the model info.

Would be good to also get @mwetter 's opinion on this.

**Comment by mwetter** [comment]
@marcusfuchs , @bramvdh91 
As for district heating/cooling pipes, both uses cases, e.g., set the required pressure loss per meter (conceptual design), or set the pipe diameter (detailed design) is useful, I think it is good to provide users both options.
Given the discussions on https://github.com/bramvdh91/modelica-annex60/issues/24, maybe it would be clearest to have two separate models that extend from the same base class but provide the different parameters that are now exposed for `use_dh=true` or `use_dh=false`?

I think that setting `use_dh=False` but then using `dh` will confuse users.

**Comment by bramvdh91** [comment]
I have merged this branch into `issue264_pipe` since there were some problems where `diameter` was not changed yet to `dh`.

**Comment by bramvdh91** [comment]
Maybe to add to the discussion here: I think the detailed pipe model will only need the version of the resistance where `dh` is used to calculate the transition. 
For the version where the user just wants a conceptual network where the diameters are not fixed yet, it does also not make sense to do detailed heat loss calculations. For this type of quick calculation, a simple proportional heat loss (e.g. 5% or less over the course of one year) would suffice.

**Comment by bramvdh91** [comment]
Have a look at https://github.com/iea-annex60/modelica-annex60/issues/480

**Comment by bramvdh91** [comment]
Closing this as we are now using ``HydraulicDiameter``.
