### ISSUE TITLE
Delete obsolete issue264 branches

### ISSUE THREAD

**Issue by bramvdh91** [bramvdh91/modelica-annex60#25]
There are a lot of branches named issue264_*. I think it is best to delete those we don't need anymore. 
- [x] carles
- [x] heatPort
- [x] Pipe_SpatialDistReport
- [x] state
- [x] timeDelay

Please indicate whether you will be needing a certain branch or (if it was your branch) if you do not need it any longer. (Tick means keep, no tick means not needed)
Personally, I believe the branch issue264_state can go.

@carlesRT @marcusfuchs @GersHub  Could you have a quick look and let me know if we still need these branches or not?

**Comment by marcusfuchs** [comment]
Just deleted the `pipeUseCases` branch. I haven't been working on any of the other mentioned branches, so from my side no problems in deleting them. Good initiative to clean this up.

**Comment by bramvdh91** [comment]
I believe that except for issue264_heatPort all changes have been merged in the main branch. I will start by deleting the oldest branches.

**Comment by bramvdh91** [comment]
Deleted all branches that have been merged before or whose changes have been added otherwise.
