### ISSUE TITLE
Time to remove tau_unused?

### ISSUE THREAD

**Issue by marcusfuchs** [bramvdh91/modelica-annex60#41]
Can we safely remove the `tau_unused` component from `Annex60.Experimental.Pipe.PipeHeatLoss_PipeDelay` (or better: `Annex60.Experimental.Pipe.PipeHeatLoss`) or does anyone need this part? If there are no complaints, I will issue a PR with this component removed.

**Comment by bramvdh91** [comment]
@marcusfuchs Thanks for bringing this up, indeed it is time to get rid of this.
Claytex told us (see #17) that the different behaviour for connected/not connected components should be solved in Dymola 2017. I was not aware that this version is already available and just requested a download link now, but if you can already check that there is no difference in output anymore, we can remove the duplicate components. If I get it soon enough I'll check it myself. 
I'll already make a PR for merging the dropped `_PipeDelay` into the main branch, such that we can move on from this version.

**Comment by bramvdh91** [comment]
@marcusfuchs There's still a slight difference (at least when using Dassl) between the used and unused `tau`. However, I do not think this is something that we should/can solve. I will remove the extra component and make a PR.

**Comment by marcusfuchs** [comment]
I merged the PR, I also think the slight differences are not something we can solve.
