### ISSUE TITLE
Variables in PDETime_massFlow

### ISSUE THREAD

**Issue by marcusfuchs** [bramvdh91/modelica-annex60#46]
Some of the variables in `PDETime_massFlow` could be renamed.

E.g. in my opinion `v_a` sounds like velocity at port_a. Instead this and similar variables are used as 

```
  Boolean v_a "Is the fluid flowing from a to b?";
  Boolean v_b "Is the fluid flowing from b to a?";
  Boolean v_0 "Is the fluid standing still?";
```

I suggest using e.g. variable names like `isDesignFlow` and `isZeroFlow` instead. Also, the velocity `u` is currently calculated for the normalized distance between 0 and 1. I think having velocity relate to the real pipe length would be better understandable for the user. My experience was that I first struggled to find out that currently `u` is in normalized units per second, not meter per second.

If that is ok with others, I'll make a suggestion for redesigning this and push it later. At least for me, this may make further work on the models a bit easier.

**Comment by bramvdh91** [comment]
@marcusfuchs Okay for me!
However, maybe it's not needed to put too much time into this if we would decide to go towards a simpler model such as in `issue37_newDelayMod`.

**Comment by marcusfuchs** [comment]
That's a good point. I will have a look at it anyway to better understand the current implementation. E.g. I would have thought that going from normalized velocity `u` back to real velocity `v` should not have significants effects on the results, but it seems like this still influences `tau` noticeably, so we may want to stick with `u`.

**Comment by marcusfuchs** [comment]
As there are currently more important issues, I'll close this for now. Once we have decided on whether to keep this implementation or go with Bram's suggestion of 2 `tau` values we may or may not re-open this issue.
