### ISSUE TITLE
Replace AIT temperature sensors with two-port version

### ISSUE THREAD

**Issue by bramvdh91** [bramvdh91/modelica-annex60#57]
I have added a branch where the single port temperature sensors are replaced by the two-port equivalent. By activating the cooling-down function with an ambient temperature of 20°C, a better approximation of the cooling of the real sensors is achieved.
Furthermore, I would propose to make the zero-flow for substation 4 actually zero, so to remove the glitches, since they are not represented in the measurement data.

**Comment by bramvdh91** [comment]
See 4d1d758518ee48ecaa4ea0dbb4335664425bab1c

**Comment by bramvdh91** [comment]
With the two-port temperature sensors and after removing the noise of the mass flow sensor around 0, I got the following results:
![validationpipeait](https://cloud.githubusercontent.com/assets/10756543/20563922/f04a24e0-b18a-11e6-96b6-735bcbb82e9d.png)

We still seem to struggle with a quite long delay with respect to the measurements. Maybe there is something wrong with the length or diameter of the pipe?

**Comment by bramvdh91** [comment]
@carlesRT , I would prefer to use the actual outlet temperature in the paper instead of the T_out_b, since this one does not show the quick dips in the outlet temperature, whereas the figure above does show them.

**Comment by carlesRT** [comment]
Shall we use the same temperature sensors and filtered mass flow rate in point 4 for the MSL example?

**Comment by bramvdh91** [comment]
I think that’s a good idea. I forgot to make those changes in the other examples, I can add those as well. I believe that this filter is necessary because those short mass flow increases are not at all reflected in the measurements, so I suppose this is just measurement noise.
