### ISSUE TITLE
Improve initialization of ULg pipe

### ISSUE THREAD

**Issue by bramvdh91** [bramvdh91/modelica-annex60#61]
Use 17°C as initial temperature instead of 20.

**Comment by bramvdh91** [comment]
@marcusfuchs I see that the initialization is now a parameter (initial enthalpy at in- and outlet) in ``PipeLosslessPlugFlow``. Would you say it is better to make the temperature the initialization input here or are you using this parameter somewhere else already?
If not, I would propose to change the enthalpy by the temperature (bit more relatable) and calculate the enthalpy inside the component.

**Comment by bramvdh91** [comment]
@k-sartor Added initialization, yielding very good results!
![validationpipeulg](https://cloud.githubusercontent.com/assets/10756543/20716225/cebfb832-b651-11e6-9926-ef3d46b824a3.png)

**Comment by bramvdh91** [comment]
Only added initialization for ``PipeHeatLossMod``, see #63

**Comment by k-sartor** [comment]
Ok.
I will check the experimental data with the last model.

2016-11-29 16:37 GMT+01:00 Bram van der Heijde <notifications@github.com>:

**Comment by bramvdh91** [comment]
Closed by #64
