### ISSUE TITLE
Remove ``PipeHeatLossMod``

### ISSUE THREAD

**Issue by bramvdh91** [bramvdh91/modelica-annex60#63]
I don't think there are any differences between the two ``PipeHeatLoss`` models anymore. Okay to remove `` PipeHeatLoss`` and to rename ``PipeHeatLossMod``?

**Comment by bramvdh91** [comment]
If not, let's make a partial model that the two can extend from in order to avoid having to change everything twice all the time ;)

**Comment by bramvdh91** [comment]
Maybe check  #50 for keeping the two different components...

**Comment by carlesRT** [comment]
It is ok to remove one of them. they are exactly the same. 

PS: If needed it one can always check the Github history.

**Comment by bramvdh91** [comment]
This is solved by moving the component to archive.
