### ISSUE TITLE
Check conversion to IBPSA

### ISSUE THREAD

**Issue by bramvdh91** [bramvdh91/modelica-annex60#71]
I have tried to run the python conversion script as I noticed a lot of our components were not copied to the IBPSA folder. I'm not sure if everything is working now, since I had to change the pressure drop component to the new "HydraulicDiameter" FixedResistance.

Could you please check examples/tests that you consider important and see if everything is working as expected?
@marcusfuchs @GersHub @carlesRT

**Comment by carlesRT** [comment]
I do not see any major problem. But it would be good to
- propagate the `HydraulicDiameter` parameters (`ReC`, `roughness`, `fac`, `allowFlowReversal`, ...)
- `dp_nominal` is not used anymore.  We can remove it or suggest to change `HydraulicDiameter`. In this regard, `HydraulicDiameter` uses `_default ` value for `rho`, `mu`, ... it would be good to be able to edit this values. Related to #48.

**Comment by bramvdh91** [comment]
Good point.
In the meantime I am not able to compile our validation examples (ULg and AIT), and I'm a bit puzzled about the reason... Dymola gives the following on translation:
   
   ```Non-literal value.

   In nominal attribute for pipe.pipeAdiabaticPlugFlow.res.dp.
   Ignoring nominal attribute.
   In class Modelica.SIunits.
   Near file: C:/Program Files (x86)/Dymola 2017 FD01/Modelica/Library/Modelica 3.2.2/SIunits.mo, line 2
   Used in base-class pipe.pipeAdiabaticPlugFlow.res.PartialTwoPortInterface.
   Near file: C:/Users/u0094934/Documents/Dymola/modelica-ibpsa/IBPSA/Fluid/BaseClasses/PartialResistance.mo, line 3
   The DAE has 271 scalar unknowns and 271 scalar equations.

   The initial conditions are not fully specified.
```
After that, there's two errors, both the same:

   ```Not possible to compile model (0)
   The system is out of memory or resources
   Compilation of IBPSA.Experimental.Pipe.Validation.ValidationPipeULg failed.
   Note: There were translation errors that might explain the problem.
   Compiling
   Errors were found
   Warnings were issued
```
This while my computer is clearly not out of memory, and no clear message about which errors were found is given.

**Comment by carlesRT** [comment]
I Could translate and simulate the `\Validation` models (I am using Dymola 2017 and Visual Studio 2010...).

I have but a different number of scalar unknowns... I guess you posted Dymola messages related to `Validation\ValidationPipeUlg` ?

```
Translation of IBPSA.Experimental.Pipe.Validation.ValidationPipeULg:
Non-literal value.
In nominal attribute for pipe.pipeAdiabaticPlugFlow.res.dp.
Ignoring nominal attribute.
In class Modelica.SIunits.
Near file: C:/Program Files (x86)/Dymola 2017/Modelica/Library/Modelica 3.2.2/SIunits.mo, line 2
Used in base-class pipe.pipeAdiabaticPlugFlow.res.PartialTwoPortInterface.
Near file: C:/Users/carles/Documents/3_DYMOLA/Bram_Annex60/IBPSA/Fluid/BaseClasses/PartialResistance.mo, line 3
The DAE has 280 scalar unknowns and 280 scalar equations.
The variable pipe.tau_used.inp_a is not a continuous time state,
which means that existing reinit has no effect.

[...]
```

Maybe is something wrong with your repository.

**Comment by bramvdh91** [comment]
Apparently Dymola all of a sudden forgot where my C++ compiler was located... Working again now :)
